[[MDLovoFit]]
arch = "aarch64"
git-tree-sha1 = "d39b36981420ea70c5db01fbe9aa4b110016cf19"
libgfortran_version = "5.0.0"
os = "macos"

    [[MDLovoFit.download]]
    sha256 = "0017aff2f85243f5976b3e578042cec65ae8860348857ede7683a3a154b3bdc3"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "aarch64"
git-tree-sha1 = "581f53b36280fe5d65e6afed880c7f911652835b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "ee26e208df2004dc1fd2f1a8ba5b75bc869f0f14212e3d203dc685854f217577"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "aarch64"
git-tree-sha1 = "9f27a7b17a08a4b800370bf02883a24f5768b005"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "8bccdd06da4ad646e8fe347a7ff3bd24d2edcf0d2a0d3bbbde84cd3e1ecb9b48"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "aarch64"
git-tree-sha1 = "16a40d4d6545874c7caf19b5e11d174d01794045"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "70e9c486d453eb964df388ff7c214e7ffb2ecd243d6d03cd3fdd0cac84004827"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "aarch64"
git-tree-sha1 = "c70bd75efd5c1184be890516b4cd80a69819d0c8"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "16c0a0133f51eb6fc372c0c6756e01a9a2c035da7f25511e9adffb8bfe310515"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "aarch64"
git-tree-sha1 = "1dd8f6af02b136088a8813c33c671bf2ed64b37b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "04c81f5ec16e5f2efd15aa13e0ac3a09621f942aff166c8d8f256fb2c23ee9ed"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "aarch64"
git-tree-sha1 = "d49882f2d406da02fd80f0a0dcb999246bc7cbaf"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "c5d6757d3cc0089f758273bd5bcc95aec90e7188ffe0adf685457324f991876d"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "eeeb0f8ec543b39731013ecfe9f2f16ae06517e0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "98e99e8ff68d2effba17335368df0c6fc4415a2acf2398389504c7840c54b40d"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e707efd3bb2287360e42fa4aac7741e2de2d5b80"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "0732e73d0b8b40dd15b9f734dacf7784b0bdf0f4a5a30634f20ef8019cd01bd8"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dff7c7f847d42ddda8c02d5f9a7fdbd4af8cfe01"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "457d1ba91170476083c895f68ee80a12654f156a70df811cab7ee040ba25ad0f"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7de5373f6ae4f1e64b376103412d6d5b17284cb0"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "0ee1292feb410d5f2a89bf1b66fdea5fc38e9cc49661a5533fa310acd69bb11e"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "67cfa83c36fa0b1f667b50895204296e72abeaaf"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "0761fc7e366eb82366eec6b0fe32d324b9a29b7b2d9cc6a641f7eb0e377d7f0d"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "26952c2b84636fdd9390d0dffa3f9002eaab6fd3"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "645dac23a557ff80d3b2dc0845c300ef697c8fcab090889e45b4abcb2ca8ea86"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "002ca957db95bc4b4058f5d75de02f67e20293b2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "7915f48791f6d0e7698f2462f47ba4b0f94bc599bca0f514979e04e96b480588"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "94f14871df6a2d15d7df5c556cc61e563d7c84b1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "b549088e86d173dac756b70fe63e912e3b58eaf885a6eb84575da927174d5581"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "38131e313cc26dfb7df7ef5ae289b9965d88c22e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "415e6fb9cf7e81c2d3b97834b11e5e9ce063e7d26538b3ace54466817c2e5c91"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dd208e00c84612a7fd1b6b37207a0dce3129d841"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "bbabbabd744b60a247a6cb9125ec02ade308a2b211cfa7030c9934011b96fc72"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5c4b79dcab1b5963f014b8c5e129a3d2dfbd48c3"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "cf366203e4daf2d28f01d836796e2ff77e2e4eaee6f518e1f089db382fef748a"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bffafb840c87972afb4ef054ad904272ee46a912"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "ade321de39399ed3d0319fc7befd85c5f3575b5d7cb85085f03a8c18ffc95c4b"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "i686"
git-tree-sha1 = "ffcb39c39999ceb57cba2abab2664443fd2b024f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "fddba0857bab5a37ea87a2746db9e4471e01287c7605f923931fc4af2a8d9499"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.i686-linux-gnu-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "i686"
git-tree-sha1 = "7c0fb006e9dbadad24357efbbd0e4dc60c7ec908"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "be209be357015ad7f7bf16b94ac6d62ba09b4cf1f9ba252750053a45f5df951a"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.i686-linux-gnu-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "i686"
git-tree-sha1 = "279c10671b1cb09e92ac97bbce40b8bdb29a83e1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "46648fdd40450ee1e573cc1845a094b923ca15190ddf70c0e818abfc190d6ae6"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.i686-linux-gnu-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "i686"
git-tree-sha1 = "a7b4dc8e721e69bd4db4e1bb2b78ef557f5de797"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "787dee9e459ae1001a5a682d8fb652bf30cbf192780656cf3e0f13875ae4a21d"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.i686-linux-musl-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "i686"
git-tree-sha1 = "544b0afd7dbe9416908535c0ee07be8ac19fab6a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "450ebdc4f18acc28f0ab1eca3ce6219153ceb9ea379587acbc77d76d6d8865c7"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.i686-linux-musl-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "i686"
git-tree-sha1 = "80f6eaa0807b458897973418bf5e298ac58b0e2f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "525e5d6fd36e05d64a186c92adfb675b67b3b8bf2fff500a53f9eee1c23209fb"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.i686-linux-musl-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "i686"
git-tree-sha1 = "27abba29696615c7876ec5a51a8461e5f651d0df"
libgfortran_version = "3.0.0"
os = "windows"

    [[MDLovoFit.download]]
    sha256 = "d482a7f6336d7f0ea77576c30ec140b42b7d8f18b5ff4520ee676f1caaf53f0e"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "i686"
git-tree-sha1 = "fb4a8ccf2911d0b6b3e1a5742aded90ac2b3d551"
libgfortran_version = "4.0.0"
os = "windows"

    [[MDLovoFit.download]]
    sha256 = "9f1ad212bd4f0444bd62cd5270773450b16bbf4b2fdf7aaf79a2b6ad6edc1e9b"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "i686"
git-tree-sha1 = "3ffb31119f5de0966f066d8e2d8cfd38e1926291"
libgfortran_version = "5.0.0"
os = "windows"

    [[MDLovoFit.download]]
    sha256 = "ff3249fd64d2f8884e0be0c2ec4250685bae23d282ca9a8d0cdb51c4e98a9a65"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "powerpc64le"
git-tree-sha1 = "74b8981d03beb4aa12052168102e1438136cf7f0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "30fe29f9987557b15bc9b0a086c33c86e9f51bd68e5be54b898d38012594e7c4"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "powerpc64le"
git-tree-sha1 = "c310428b19be3a982fa927982f57f9f999add7ec"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "d5f03aae0be97ccc3f437420b961a87dc3563c3d085813a14b8d92a5e1848770"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "powerpc64le"
git-tree-sha1 = "0e947b3d600f317ccb93e026177cfb683955cbd8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "295897a33f92b84fb8a222d0c4d7a34751957c6556fb6a28428404d6e5133f4b"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "b0248e5660d89488db5f75862dd4fc282efac1b8"
libgfortran_version = "3.0.0"
os = "macos"

    [[MDLovoFit.download]]
    sha256 = "1a9e06a71c48b90f111af1238d7bb72477cb16a94ae1e92874988f779f474cd7"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "d46191572cf073ebbad6d36ebe0db2a51ea925e1"
libgfortran_version = "4.0.0"
os = "macos"

    [[MDLovoFit.download]]
    sha256 = "7d9a774f9b0278b1ec6afb84c33dde32c9a48ec539bd2f2d00ce726f8ee90e6f"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "ea55ac9a520b0fc03f0cd445958f7e33f421cd03"
libgfortran_version = "5.0.0"
os = "macos"

    [[MDLovoFit.download]]
    sha256 = "6cfff338078bfa40212cfea588491e6c42ee8b95385eeef305d2ea7aa8b92a1c"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "8e7a62418d549e889d12326f1f16b491906437cc"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "e43daae747e15b486a63d38480585d6b9e5562644108b751a860aed19d063660"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "61ac582e217a7c5d8e8a2cc1d067f96d8ec58f28"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "19b40f8fc6181b5e705b1fb89097993fec0409b7fa892d3bfdeb7f170fc9a0bc"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "0d871259caa988cd7ef3517e4d99ec7c9caf4494"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "816c0ba51544a305f0d505398ee8bf1f144b032216155ef878cf311d3883c5b4"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "59c78c94e74f70617e83cb9b4a8a2a79bf0e7a13"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "17e37a0b5578a4e36c1f055fa5aaeb490fcad04a397ad8549e357348d7b42f99"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "aa4e42b4fae025e4a10c1df05e61a24d4f87dbc0"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "14af0104220ffa7ad65ee55c49e324c05d82be89d9faa8dcbee7c4777a38d3e2"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "9900d30f7e56c27edab85154c18eb2bc8e6de1b8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "433e8bbcf7e90137f48167332d7842efab285024e5cf5fdf9f950107e00601bd"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "ddc89ab0aa6a483c1882e8b783f12f0d5ce0c5cd"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MDLovoFit.download]]
    sha256 = "c82d54ae4b6eb9b18437fd2049231a3064fe36c219b7e50cbcb53e95df76744e"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "bca8104667c902ba0043aeed7c9cf6fdcc3a2a5e"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MDLovoFit.download]]
    sha256 = "ebeb43e735954ac39e16efbe8ffbb42c72f180ec098df45f0e69063a1aa27388"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "6222feb05b8c9b4827c722628c0b066d0753a4e7"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MDLovoFit.download]]
    sha256 = "8015d2fe668965200bb4c45e4ed70fa93b0c6b6fac8fe2d49907cbdf9258c623"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "4617959c89ae5ed78a62349a29906848a72b08f4"
libgfortran_version = "3.0.0"
os = "windows"

    [[MDLovoFit.download]]
    sha256 = "027505988adeb9ad037d903b6fb357554030aecd352cde0cf2d83c635bc832ba"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "c549efcdddda4a958e1b4aeffac56c0409beb7eb"
libgfortran_version = "4.0.0"
os = "windows"

    [[MDLovoFit.download]]
    sha256 = "f66d75f837a4261812a0fedcf5d4dbcabd20597ac89977c24d5b5b8d7746017e"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "52b572de9637de15eb805fb4f4a7dff319ac4202"
libgfortran_version = "5.0.0"
os = "windows"

    [[MDLovoFit.download]]
    sha256 = "0a4d3d0240e52e0b2d571315b07c672bac9c1dd776098bfa15259c2d07995d9c"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.1+0/MDLovoFit.v20.1.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
