[[MDLovoFit]]
arch = "aarch64"
git-tree-sha1 = "c1813e65831378dce08d10d8b63f456886a2d8c1"
libgfortran_version = "5.0.0"
os = "macos"

    [[MDLovoFit.download]]
    sha256 = "4e0d50adf5119b3aec5259772d2838202dbc794c6d98f60ebe0f10cb69ba6c58"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "aarch64"
git-tree-sha1 = "ee4c212e7241c2550ec6e7a91a7a0b411c18f47c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "e9732829f680675f064140f2011b1786d6a956284de0b92aa9d141bbfca8d3fe"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "aarch64"
git-tree-sha1 = "cee4cdb8bef3639fc015eae4c73cd158ee0e1b48"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "fb6291360b09edeb300bad9edfc65b7da9644891b141fa77188765e30b598496"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "aarch64"
git-tree-sha1 = "a6d86745e26355ffce5e63421fef2ecde6714844"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "9a1b3e5de71c318a5731ee8d4e858d8f819c7c88e7572c73b57ba62a93617052"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "aarch64"
git-tree-sha1 = "7adc5fd39d993d96d7fb544b329b57682c247f0d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "d1f8247a2ef537107daecde8bda169d619c7cac7d0d8001021b208d2ba9404bd"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "aarch64"
git-tree-sha1 = "7ef90a273a31c051412cd452627b2548f6d5a37c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "0066fa56b8c295f436d8b197ba607e62784d8a00c87a2c2f398160f1568f4b69"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "aarch64"
git-tree-sha1 = "1352fccea6f520a4fe58716de8f988978418bbc9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "794a1990196d00fbef64719d5f335c27e9de9fdb78362a33877eb75c2aee0da7"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ccb1847b48b02bd04369f7bbd66e66f505127eb9"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "311f1e5de58c1f99c8539565b2f0fa78eaccef9e641f8636247019542274bb9e"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "980f3e6f06c1bfaac634167fd55b832c0b9a191f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "335658794e59bb58078e0f2bc299b03c70522f1a19af7bd07b987954428b37f3"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "51a9573366282509373f6acd8dd13af6cdd52e84"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "d2fa61a19bbe166400c59f241daa93554454043a6a1691e2f379c4c3014a469c"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1b34c9cc174db15cf885521f11ed130378fb8bb5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "e73c261607b26f8e6fc5f13551f3ae731c73f88a86ab58107f46a304e6b8708c"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "56d4ad099315c1e7aa2b09f8eb6a7aaf32e9bcaa"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "5b59bda67ab0ec8fbda1d2fbfb0708d60e2ce00ed97cd38cfce64097c6e91aa5"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1d38077139dda1ace47693b1893212a1f7abce0f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "ff78d5126a8b3f9332a2e76f72a3a7fbd2a02b9ae6036c100b52adf8cb0cc21b"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0e907a6ec0f8c68340d5b87bac1da4c0e5bf0fda"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "3785777da43f5386025131609d31f77d7c7a9206394740874aa0a1a9323b0465"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1a644dc4efc46791e6d9c6f6e54ab6450084745c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "86c600cba035a7add728a40ba362fb83c6672fce33b98f26f09920397390c0c0"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c15c076f2967d4f4ca9176df018de5cf856f0a8f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "b55ca6156f8de4781f72d1eecb2898e62b531c1702372d5de77000d2a34dda2d"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c67b034fb82a26d5f84e86b67483b3ebe4496813"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "55a682671c02f5558e4d67f2cd65e330c3e7b5f720ca980b1c834c7f0cfe426d"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fc4df51a25a35dffdb6597a4050ac01a4900fb18"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "3c9d36b797d99c04c83dc951af7c6c3d5e30f745af788d4d39f3899f4ad274ba"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b2a95f21457273162e8f03a085f4bd3527726d89"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "8c8c06f5d49a518811c3824db9e98fd185422234117b4964cbe629aeffd33dfe"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "i686"
git-tree-sha1 = "a0eff60287a96f38b084a2ec2972a389b87bf339"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "efececa78bb4f71951053654bd7a92ea3e8e5056ebc4ccf7b71f02e7c72ce92c"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.i686-linux-gnu-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "i686"
git-tree-sha1 = "3697a17ba60a02b69acd56a04ea7595beda095c4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "a995c0649bf6b4de4d9a61ee1bb2a262d635ae708863abb635c4fac4431b6cf2"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.i686-linux-gnu-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "i686"
git-tree-sha1 = "91b8067700a521c2787611ae08411b21106b8024"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "aa0e0bbebbcf79e82143858a910f0cf02998f28e42d8cda35314c2e50859772d"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.i686-linux-gnu-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "i686"
git-tree-sha1 = "36569203db60514875f91dcdf5921301850c8a8f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "2f2d94127423a6cd437f9988726e158a83a54436f5ebb581d0505d2ba6ed7f9b"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.i686-linux-musl-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "i686"
git-tree-sha1 = "9f707981b903921f1aed682b93924fa4825399d4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "cb081428cc59d515f09666e7f402b4e6a76a65816e7d7cfb50d47874e95965af"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.i686-linux-musl-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "i686"
git-tree-sha1 = "25a1789fca0ee1834bb49d20b9f085db4c2b2b9a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "92f1f88edfc856da79cd1fd2183c48d98b6fdcb875718369e4c5f12ab0f0cb84"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.i686-linux-musl-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "i686"
git-tree-sha1 = "2e63ab805d0d3c929df2cec9753b9674a8028186"
libgfortran_version = "3.0.0"
os = "windows"

    [[MDLovoFit.download]]
    sha256 = "944741dd9eee4d9be473471b25005f49b0fb7cd1bdb437951ddc5908c918053b"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "i686"
git-tree-sha1 = "53c4eccbefe5eaec4a289f597065329bc945fb72"
libgfortran_version = "4.0.0"
os = "windows"

    [[MDLovoFit.download]]
    sha256 = "7a41282d1f52b3aede5c0c84d40a358a8ff02e2a6a9cfa6519f9d24f57f84fef"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "i686"
git-tree-sha1 = "cd4ddfe6007f19d9d2b436d5e7d2df5fdac3abb2"
libgfortran_version = "5.0.0"
os = "windows"

    [[MDLovoFit.download]]
    sha256 = "100617ab5385d9f4ced48bfa1232ec4daeede28ff91c35a58389d9fed3542f99"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "powerpc64le"
git-tree-sha1 = "4b23f4ec3642adb7354c9a797d95fecb0e74d45b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "02b7071298f6cd722b1664b7abcc4b80a935da467c718f60822faae48a0861d9"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "powerpc64le"
git-tree-sha1 = "7b5e1381679187f8aadf8b5ff023e20d9236172b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "7baef52c6117ecf71c54713cc33c8d0f1ca143275a125bd066392f9082faf730"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "powerpc64le"
git-tree-sha1 = "f81a0b42ca43b64ff49bf52b3f28adeac50a35a5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "4016e433146fe157cd6a7e6a71fd6672e9441d76d9d4989fd7b0b7f3a32bfd2f"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "27182307580546e75bb0c4ce2d23c1300719c6e9"
libgfortran_version = "3.0.0"
os = "macos"

    [[MDLovoFit.download]]
    sha256 = "9a2a0c5cff633801a52094b74f821f17b49b83bf263bfc4ddc5a89ccbb1863b7"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "bb05985cd6965cc587614551c7a39dd699856276"
libgfortran_version = "4.0.0"
os = "macos"

    [[MDLovoFit.download]]
    sha256 = "98c246dbe1ef7229f57651b8b58c38486ab37b08dac92067c36ca028cba9107f"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "a02c9a1c2a465efb19df730f1d16e95ba6f118a7"
libgfortran_version = "5.0.0"
os = "macos"

    [[MDLovoFit.download]]
    sha256 = "db8ace95708e793d4721905c55c6908a6067ee0a4623cabe261d3c80f2d17656"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "5214b6ee57beb17ae41d60b63766db420152ffdd"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "eac5ee61516c33c3ff2fab56be77eaec761bbf893e255965a40ac208a7efbe52"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "10af2648ab87e3f51171fd20072873cdf4b6cf2e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "c32c45174c557f6bc267064fdfe357617df6eebbcb03df157c67943f34e8a306"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "a0426bbe45cba70c0b98a5abc8fe8d689bd7a5ff"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "b9c4f3013bfdb0285c48dca495b734f15a4b469378283463aee32a5d2dfe22da"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "e73f536c41df2a3bd54513a6c3ecabfdb01242d4"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "378bbc85ffdaaf963f9176091053698621e832b32198756b13254a74666e8cd9"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "50a4581eb8b0162d4895199e07125ab3aca884e0"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "746146ecc540e702f983d777feb6acb0a645077076cd406c5a2b24ef045c843c"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "2fec27dff0caa1b205bd8717249eb897e45a795c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MDLovoFit.download]]
    sha256 = "544084655444b9ac70b0f0bf8d75a1cdef81796031d0620b19e11cc23ca93750"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "50361edf7c324671a2e4a61fb92d20ad4cad68cb"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[MDLovoFit.download]]
    sha256 = "fbeca9c6cf37176b08054fbd75d1a637911abceac2764dd5afd86dbe611719cf"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "29b77a8fe6e709e170337054f89f53a9daa749e3"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[MDLovoFit.download]]
    sha256 = "f7c5e82ab49723fcfc8b212047bdd399b1a7514aa86155c0537aca6acd134f3e"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "ab4aacd24bb820615f848cae4d3275d900585b9a"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MDLovoFit.download]]
    sha256 = "22241b0b65d24ae923b6fbeb7f37dd3c09c0d79086928c3f56a42c2bc79aa7e6"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "0962d4e443b268aaae35e58daa798d9a7c528ab7"
libgfortran_version = "3.0.0"
os = "windows"

    [[MDLovoFit.download]]
    sha256 = "964397187060aa493d693e48febc89cf6890f28f15b1e7ccfb28bc39d3399107"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "eacd5f48bfbeebdb9e0fb922bd244d6042ef5655"
libgfortran_version = "4.0.0"
os = "windows"

    [[MDLovoFit.download]]
    sha256 = "03a149aa124db6a234b7b338d92ab1f44406db1fb32a4e3f0b76cd3634679a59"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MDLovoFit]]
arch = "x86_64"
git-tree-sha1 = "240515c31edd273928bb71161e5b02930360ab01"
libgfortran_version = "5.0.0"
os = "windows"

    [[MDLovoFit.download]]
    sha256 = "42b6bb8a05f4cf123659280559ad4f406c162480c4f0e7d888707a86a3a3282a"
    url = "https://github.com/JuliaBinaryWrappers/MDLovoFit_jll.jl/releases/download/MDLovoFit-v20.1.0+0/MDLovoFit.v20.1.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
